### ISSUE TITLE
Dark mode doesn't work on Chrome

### ISSUE THREAD

**Issue by Razomi** [Nwko/Nox#8]
It seems like https://nwko.github.io/Nox/dev doesn't work on Chrome but it works fine on FireFox and Microsoft Edge ;w;

**Comment by Nwko** [comment]
it doesn't work on Opera/GX either qwq

**Comment by Nwko** [comment]
Think it got fixed in https://github.com/Nwko/Nox/commit/8600b3559127f3c40ccc31d30a5fa5fea5df2b07 :D?
